### PR TITLE
FIX: Add missing epics-base dependency.

### LINKED ISSUE #15: Missing epics-base dependency
Issue:
After #12 got merged, pyepics should add epics-base as a dependency.

### PR DESCRIPTION
**Pull request by hhslepicka**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

After merged it closes #15

### CODE REVIEW

**Comment by hhslepicka** [comment]
@conda-forge-admin, please rerender

**Comment by hhslepicka** [comment]
@tacaswell I just added the suggested command test (https://github.com/conda-forge/pyepics-feedstock/pull/14/files#r310397905) .

**Comment by tacaswell** [comment]
The failures look like the are because `{ python }` get the parameterized path from the build env not from the test env which is gone by the time we hit the tests.  Maybe just `python` and hope it sorts it self out?

**Comment by mrakitin** [comment]
What happens if `python` is included in the test requirements list as well?

**Comment by tacaswell** [comment]
python is in the run requriments so if the package is installed into the enviroment then python must also be installed.

I suspect the problem is that the template is evaluated once at the beginning in the build environment (in our home version of this we just call `python`).

**Comment by hhslepicka** [comment]
@mrakitin I am looking into it right now.
It is due to the fact that epics-base is not setting properly the environment variables for Windows.
It will probably result into a PR to `epics-base-feedstock` to fix it but I will keep you posted here.

**Comment by hhslepicka** [comment]
Closing in favor or #17

**Pull request closed without merging**
